development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dangt85_blogdev
  pool: 5
  username: dangt85_blog
  password: /I6>%|ugJ?Wm
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: blog_test
  pool: 5
  username: blog
  password: cl4v3
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: dangt85_blog
  pool: 5
  username: dangt85_blog
  password: /I6>%|ugJ?Wm
  host: localhost

