development:
  :address: 0.0.0.0
  :port: 25
  :authentication: plain
  :user_name: cyg_server
  :password: p422w0rd
production:
  :address: 0.0.0.0
  :port: 25
  :authentication: plain
  :user_name: cyg_server
  :password: p422w0rd
